export const Tips = [
    "An apple a day keeps the doctor away 🍎",
    "Drink water like it’s your superpower 💧",
    "Sleep is your secret weapon 😴",
    "Strong body, strong mind – get moving! 🏃‍♂️",
    "Junk food = junk mood 🍟➡️😕",
    "Veggies are your vitamin superheroes 🥦🦸",
    "Screens off, dreams on 📵🌙",
    "Breathe in calm, breathe out stress 🧘",
    "Protect your peace – mental health matters 🧠💖",
    "Small workouts, big wins 💪",
    "Fresh air fixes everything 🌳",
    "Healthy friends = healthy habits 🤝",
    "Don’t skip breakfast – fuel your day 🍳",
    "Balance is better than perfection ⚖️",
    "Water before soda, always 🥤❌💧✅",
    "Be kind to your mind and body 💗",
    "Stretch it out – your body will thank you 🧘‍♀️",
    "Your future self will thank you 🙌",
    "Health isn’t a trend – it’s a lifestyle 🌟"
  ];